# Generated by Django 5.2.1 on 2025-05-11 16:04

import apps.cv.models
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=apps.cv.models.uplaod_to)),
                ("file_name", models.CharField(max_length=255)),
                ("raw_output", models.TextField(blank=True, null=True)),
                (
                    "candidate_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "candidate_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "candidate_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "candidate_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("experience_score", models.FloatField(blank=True, null=True)),
                ("achievement_score", models.FloatField(blank=True, null=True)),
                ("skill_score", models.FloatField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cvs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("degree", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gpa", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "db_table": "educations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "proficiency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "db_table": "languages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skill", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "proficiency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "db_table": "work_experiences",
                "ordering": ["-created_at"],
            },
        ),
    ]
