# Generated by Django 5.2.1 on 2025-05-11 16:06

import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("year", models.CharField(blank=True, max_length=20, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "db_table": "achievements",
                "ordering": ["-created_at"],
            },
        ),
    ]
