# Generated by Django 5.2.1 on 2025-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="sync_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
