# Generated by Django 5.2.1 on 2025-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0008_cv_candidate_category_alter_achievement_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="gpa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="year",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
