# Generated by Django 5.2.1 on 2025-05-15 13:13

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0002_add_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CvProcessedPerDay",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("total_processed", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_processed_per_day",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CvProcessedPerWeek",
            fields=[
                ("week", models.DateField(primary_key=True, serialize=False)),
                ("total_processed", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_processed_per_week",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CvScoreAvgPerWeek",
            fields=[
                ("week", models.DateField(primary_key=True, serialize=False)),
                ("avg_score", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_score_avg_per_week",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CvScoreDistribution",
            fields=[
                (
                    "score_bucket",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("total", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_score_distribution",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CvUploadedPerDay",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("total_uploaded", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_uploaded_per_day",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CvUploadedPerWeek",
            fields=[
                ("week", models.DateField(primary_key=True, serialize=False)),
                ("total_uploaded", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_uploaded_per_week",
                "managed": False,
            },
        ),
    ]
