# Generated by Django 5.2.1 on 2025-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("process", "Process"),
                    ("open", "Open"),
                ],
                default="created",
                max_length=255,
            ),
        ),
    ]
