# Generated by Django 5.2.1 on 2025-05-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatsession_last_result"),
        ("job", "0002_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="job.job",
            ),
        ),
    ]
