# Generated by Django 5.2.1 on 2025-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatsession_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="followup_action",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
